version: '2'
services:
  opencycle:
    build: ./
    env_file:
      - .env.testing
    environment:
      - "DB_HOST=database"
  database:
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=opencycle"
      - "POSTGRES_USER=homestead"
      - "POSTGRES_PASSWORD=secret"
